# Generated by Django 3.2.5 on 2023-09-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0003_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
