# Generated by Django 3.2.5 on 2023-09-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0008_auto_20230922_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roles',
            new_name='role',
        ),
    ]
